### ISSUE TITLE
schemas different from public crash with 'relation "objetives" does not exist'

### ISSUE THREAD

**Issue by hlas** [michaelsogos/pg-diff-api#2] opened 2020-11-30 13:55 UTC
For other schemas than the user's default:

https://github.com/michaelsogos/pg-diff-api/blob/f5ad3e267ef229c91d6184f85d5f66ebd2e5d3af/src/api/CatalogApi.js#L19
should be:
`INNER JOIN pg_class c on (t.schemaname||'.'||t.tablename)::regclass = c.oid `

**Comment by JonathonCwik** [comment] 2021-01-19 17:56
@michaelsogos I came here to create the same issue. Can you please update or give one of us the ability to?

**Comment by michaelsogos** [comment] 2021-01-24 12:00
Dear @hlas and @JonathonCwik 

The suggestion is not correct as it is based on the full query written in CatalogApi.js.

Of course it could be an error for multiple schemas with same table names.
Let me investigate with some unit test.

**Comment by michaelsogos** [comment] 2021-01-24 12:07
Dear @JonathonCwik and @hlas 

Can some of you give me backup of database (without data) in order to check it?
At first stage the unit test return the right result, and the mentioned query is ok as it is.

So i guess your error will come later on the code, but actually i cannot reproduce your error.

**Comment by JonathonCwik** [comment] 2021-01-24 15:03
Yeah, I'll get you something within the next 8 hours.On Jan 24, 2021 6:07 AM, Michael Sogos <notifications@github.com> wrote:
Dear @JonathonCwik and @hlas
Can some of you give me backup of database (without data) in order to check it?
At first stage the unit test return the right result, and the mentioned query is ok as it is.
So i guess your error will come later on the code, but actually i cannot reproduce your error.

**Comment by JonathonCwik** [comment] 2021-01-24 18:35
@michaelsogos Here's how I setup a test to make replication easy:

Source Schema Script:

```
CREATE SCHEMA schema_one;
CREATE TABLE schema_one.table_name
(
    id  uuid not null
        constraint table_name_pk
            primary key,
    num integer
);
```

Target Schema Script

```
CREATE SCHEMA schema_one;
```

Diff Config:

```
{
    "dev": { 
        "sourceClient": { 
            "host": "localhost", 
            "port": 5432, 
            "database": "**source**", 
            "user": "postgres",
            "applicationName": "pg-diff-cli" 
        },
        "targetClient": {
            "host": "localhost",
            "port": 5432,
            "database": "**target**",
            "user": "postgres",
            "applicationName": "pg-diff-cli"
        },
        "compareOptions": { 
            "author": "Test",
            "outputDirectory": "./",
            "getAuthorFromGit": false,
            "schemaCompare": {
                "namespaces": ["public", "schema_one"],          
                "dropMissingTable": true, 
                "dropMissingView": true, 
                "dropMissingFunction": true, 
                "dropMissingAggregate": true, 
                "roles": ["postgres"] 
            },
            "dataCompare": { 
                "enable": false, 
                "tables": []
            }   
        }      
    }
}
```

And running: `pg-diff -c dev dev_upgrade` errors out with `"table_name" does not exist`.

I tracked down the issue like @hlas back to where he did, and found this stackoverflow with a similar issue:
https://stackoverflow.com/questions/38825020/postgresql-relation-doesnt-exist

**Comment by JonathonCwik** [comment] 2021-01-29 18:53
@michaelsogos Were you able to replicate with those steps?

**Comment by michaelsogos** [comment] 2021-01-30 10:13
@JonathonCwik 

Give me some hours and it will be fixed 😄

**Comment by michaelsogos** [comment] 2021-01-30 13:22
Ok @JonathonCwik  and @hlas 

Fixed on 1.1.0, can you please give a try and let me know here ?

**Closed as completed by michaelsogos** 2021-01-30 13:22 UTC
Labels: bug

**Comment by JonathonCwik** [comment] 2021-01-31 02:31
@michaelsogos Looks great! Thanks!

**Comment by michaelsogos** [comment] 2021-01-31 11:15
> @michaelsogos Looks great! Thanks!

You are welcome.
